# Generated by Django 4.1.3 on 2022-11-06 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogery', models.CharField(max_length=100)),
                ('sub_catogery', models.CharField(max_length=100)),
                ('mrp', models.IntegerField(default=10)),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 11, 6, 13, 21, 57, 96077))),
            ],
        ),
    ]
