# Generated by Django 4.1.3 on 2022-11-06 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_adddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddata',
            name='total',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='adddata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 17, 13, 48, 513673)),
        ),
    ]
